### PR TITLE
Fix verify WP CLI command.

### LINKED ISSUE #39: `verify` CLI command successful despite S3_ constants not defined
I'm testing S3-Uploads (master branch) on a server. I did not define S3_UPLOADS_BUCKET, S3_UPLOADS_KEY, or S3_UPLOADS_SECRET in `wp-config.php` yet and tried to run `wp s3-uploads verify`:

```
cptv@nj:~/www$ wp s3-uploads verify
Success: Looks like your configuration is correct.
Attempting to upload file /home/[...]/www/wp-content/uploads/484304978.jpg
File uploaded to S3 successfully
Attempting to delete file /home/[...]/www/wp-content/uploads/484304978.jpg
File deleted from S3 successfully

cptv@nj:~/www$ wp s3-uploads ls
Error: Error retrieving credentials from the instance profile metadata server. When you are not running inside of Amazon EC2, you must provide your AWS access key ID and secret access key in the "key" and "secret" options when creating a client or provide an instantiated Aws\Common\Credentials\CredentialsInterface object. ([curl] 28: Connection timed out after 5006 milliseconds [url] http://169.254.169.254/latest/meta-data/iam/security-credentials/)
```

Shouldn't `wp s3-uploads verify` be failing as there's no credentials listed anywhere?

### PR DESCRIPTION
**Pull request by fklein-lu**
- The command now first verifies that the necessary constants are set.
- The copy and delete operations are now done on the S3 instance,
verifying that the setup is correct.

Fixes #39.

### CODE REVIEW

**Comment by mattheu** [comment]
Ah sorry thought I had merged this one!

**Comment by fklein-lu** [comment]
No problem, you did the reviewing part, which is most of the work. :)

File: inc/class-s3-uploads-wp-cli-command.php [hunk 1]
```diff
@@ -403,6 +407,29 @@ private function recurse_copy($src,$dst) {
 		}
 		closedir($dir);
 	}
+
+	/**
+	 * Verify that the required constants for the S3 connections are set.
+	 *
+	 * @return bool true if all constants are set, else false.
+	 */
+	private function verify_s3_access_constants() {
```
Comment (joehoyle) [inline inc/class-s3-uploads-wp-cli-command.php]: @fklein-lu in the case of `S3_UPLOADS_USE_INSTANCE_PROFILE` being true, the constants for key / secret are not actually required. Could you create an issue and patch that, thanks!
