### PR TITLE
Remove upload-attachments WP CLI command and fix upload-directory

### LINKED ISSUE #254: Auto Uploading, Upload directory is not Working
I have installed the latest S3-Uploads and configured the same.

I am able to verify S3-Uploads, Enable S3-Uploads and also do migrate-attachments.

But, when I upload a new image, it is not automatically uploading it to s3 and also when I try to upload directory, it is returning to new line with no response.

I tried adding loggers into the upload directory command as below,

`
public function upload_directory( $args, $args_assoc ) {

		$from = $args[0];
		$to = '';
		if ( isset( $args[1] ) ) {
			$to = $args[1];
		}

		$s3 = S3_Uploads::get_instance()->s3();
		$bucket = strtok( S3_UPLOADS_BUCKET, '/' );
		$prefix = '';

		if ( strpos( S3_UPLOADS_BUCKET, '/' ) ) {
			$prefix = trailingslashit( str_replace( strtok( S3_UPLOADS_BUCKET, '/' ) . '/', '', S3_UPLOADS_BUCKET ) );
		}

		WP_CLI::log('URL ' . $prefix . $to);
		WP_CLI::log('Bucket ' . $bucket);
		WP_CLI::log('From ' . $from);
		try {
			WP_CLI::log('Entering');
			$s3->uploadDirectory(
				$from,
				$bucket,
				$prefix . $to,
				array(
					'debug'       => true,
					'params'      => array( 'ACL' => 'public-read' ),
					'builder'     => new S3_Uploads_UploadSyncBuilder( ! empty( $args_assoc['dry-run'] ) ),
					'force'       => empty( $args_assoc['sync'] ),
					'concurrency' => ! empty( $args_assoc['concurrency'] ) ? $args_assoc['concurrency'] : 5,
				)
			);
			WP_CLI::log('Completed');
		} catch ( Exception $e ) {
			WP_CLI::log('Error' . $e);
			WP_CLI::error( $e->getMessage() );
		}
	}
`

But the output that I get is as below,

**URL wp-content/uploads/2018/08
Bucket BucketName
From wp-content/uploads/2018/08
Entering**

I am not getting the Completed logger nor any error in WC Log.

Kindly help me resolve the same.

### PR DESCRIPTION
**Pull request by joehoyle**
`upload-attachments` is pretty useless, as it requires _all_ media files be in the attachment metadata, which isn't a great assumption. REally upload-directory is much more prefered and simpler. ASs it happens, that's be broke for quite some time, so finally fixing it!

Fixes #254, #130, #100, #266, #269, #147

### CODE REVIEW

File: inc/class-s3-uploads-wp-cli-command.php [hunk 1]
```diff
@@ -310,26 +224,21 @@ public function upload_directory( $args, $args_assoc ) {
...
-				$prefix . $to,
-				array(
-					'debug'       => true,
-					'params'      => array( 'ACL' => 'public-read' ),
-					'builder'     => new S3_Uploads_UploadSyncBuilder( ! empty( $args_assoc['dry-run'] ) ),
-					'force'       => empty( $args_assoc['sync'] ),
-					'concurrency' => ! empty( $args_assoc['concurrency'] ) ? $args_assoc['concurrency'] : 5,
-				)
-			);
+			$manager = new \Aws\S3\Transfer( $s3, $from, 's3://' . S3_UPLOADS_BUCKET . '/' . $to, $transfer_args );
```
Comment (rmccue) [inline inc/class-s3-uploads-wp-cli-command.php]: This class should be `use`d.

Comment (roborourke) [reply inc/class-s3-uploads-wp-cli-command.php]: @rmccue updated it.
